apiVersion: v2
name: app-sorba
description: Sorba Helm Chart
type: application
version: 0.2.8
appVersion: "0.2.0"
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png

dependencies:
  - name: vernemq
    version: 1.6.12
    repository: https://miguelciego.github.io/charts/
    condition: vernemq.enabled
  - name: cert-manager
    version: 1.10.0
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: ingress-nginx
    version: 4.3.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: kubernetes-dashboard
    version: 5.11.0
    repository: https://kubernetes.github.io/dashboard/
    condition: kubernetes-dashboard.enabled
  - name: is-pattern-1
    version: 5.11.05
    repository: https://miguelciego.github.io/charts/
    condition: is-pattern-1.enabled
  - name: am-pattern-1
    version: 4.1.01
    repository: https://miguelciego.github.io/charts/
    condition: am-pattern-1.enabled
  - name: grafana
    version:  7.6.19
    repository: https://miguelciego.github.io/charts/
    condition: grafana.enabled
  - name: mysql-sorba
    version: 9.4.1
    repository: https://miguelciego.github.io/charts/
    condition: mysql-sorba.enabled
  - name: phpmyadmin
    version: 10.3.5
    repository: https://charts.bitnami.com/bitnami
    condition: phpmyadmin.enabled
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: influxdb
    version: 4.12.0
    repository: https://helm.influxdata.com/
    condition: influxdb.enabled
  - name: ml-trainer-api
    version: 2.39.1
    repository: https://miguelciego.github.io/charts/
    condition: ml-trainer-api.enabled
  - name: ml-ui
    version: 2.39.1
    repository: https://miguelciego.github.io/charts/
    condition: ml-ui.enabled
  - name: mqtt-to-influxdb-2y
    version: 2.39.1
    repository: https://miguelciego.github.io/charts/
    condition:  mqtt-to-influxdb-2y.enabled
  - name: ng-api-gateway
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: ng-api-gateway.enabled
  - name: platform-ui
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: platform-ui.enabled
  - name: preferences-api
    version: 2.39.1
    repository: https://miguelciego.github.io/charts/
    condition: preferences-api.enabled
  - name: rtdb-sync-pub
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: rtdb-sync-pub.enabled
  - name: rtdb-sync-sub
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: rtdb-sync-sub.enabled
  - name: events-middleware
    version: 2.39.3
    repository: https://miguelciego.github.io/charts/
    condition: events-middleware.enabled
  - name: identity-ui
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: identity-ui.enabled
  - name: identity-api
    version: 2.39.3
    repository: https://miguelciego.github.io/charts/
    condition: identity-api.enabled
  - name: messages-mediator
    version: 2.39.3
    repository: https://miguelciego.github.io/charts/
    condition: messages-mediator.enabled
  - name: oee-engine
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: oee-engine.enabled
  - name: oee-ui
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: oee-ui.enabled
  - name: sde-socket
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: sde-socket.enabled
  - name: task-flows-backend
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: task-flows-backend.enabled
  - name: task-flows-frontend
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: task-flows-frontend.enabled
  - name: uuid-gen-api
    version: 2.39.6
    repository: https://miguelciego.github.io/charts/
    condition: uuid-gen-api.enabled
  - name: tree-api
    version: 2.39.3
    repository: https://miguelciego.github.io/charts/
    condition: tree-api.enabled
  - name: vpn-spa
    version: 2.39.1
    repository: https://miguelciego.github.io/charts/
    condition: vpn-spa.enabled
  - name: tenant-management-api
    version: 2.39.1
    repository: https://miguelciego.github.io/charts/
    condition: tenant-management-api.enabled
  - name: tenant-management-ui
    version: 2.39.1
    repository: https://miguelciego.github.io/charts/
    condition: tenant-management-ui.enabled
  - name: sorba-identity-api
    version: 2.39.1
    repository: https://miguelciego.github.io/charts/
    condition: sorba-identity-api.enabled
  - name: alerting-engine
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: alerting-engine.enabled
  - name: notification-engine
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: notification-engine.enabled
  - name: dashboard-reporter
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: dashboard-reporter.enabled
  - name: alerting-middleware
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: alerting-middleware.enabled
  - name: iot-connectors
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: iot-connectors.enabled
  - name: ml-auto-learning
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: ml-auto-learning.enabled
  - name: ml-predictor
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: ml-predictor.enabled
  - name: cloud-data-ingestion
    version: 2.39.2
    repository: https://miguelciego.github.io/charts/
    condition: cloud-data-ingestion.enabled
