apiVersion: v2
name: app-sorba
description: Sorba Helm Chart
type: application
version: 0.2.0
appVersion: "0.2.0"
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png

dependencies:
  - name: vernemq
    version: 1.6.12
    repository: https://vernemq.github.io/docker-vernemq 
    alias: apache1
    condition: vernemq.enabled
  - name: cert-manager
    version: 1.10.0
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: ingress-nginx
    version: 4.3.0
    repository: https://kubernetes.github.io/ingress-nginx 
    condition: ingress-nginx.enabled
  - name: kubernetes-dashboard
    version: 5.11.0
    repository: https://kubernetes.github.io/dashboard/ 
    condition: kubernetes-dashboard.enabled
  - name: is-pattern-1
    version: 5.11.0-5
    repository: https://helm.wso2.com 
    condition: is-pattern-1.enabled
  - name: am-pattern-1
    version: 4.1.0-1
    repository: https://helm.wso2.com
    condition: am-pattern-1.enabled
  - name: grafana
    version: 8.2.14
    repository: https://charts.bitnami.com/bitnami 
    condition: grafana.enabled
  - name: mysql
    version: 9.4.1
    repository: https://charts.bitnami.com/bitnami 
    condition: mysql.enabled
  - name: phpmyadmin
    version: 10.3.5
    repository: https://charts.bitnami.com/bitnami 
    condition: phpmyadmin.enabled
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami 
    condition: redis.enabled
  - name: influxdb
    version: 4.12.0
    repository: https://helm.influxdata.com/
    condition: influxdb.enabled
  - name: auto-deploy-app
    version: 2.39.0
    repository: https://miguelciego.github.io/charts/
    condition: auto-deploy-app.enabled
    alias: uuid-gen-api
  - name: auto-deploy-app
    version: 2.39.0
    repository: https://miguelciego.github.io/charts/
    condition: auto-deploy-app.enabled
    alias: tree-api 
