# Default values for sorbapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

vernemq:
  enabled: false
cert-manager:
  enabled: false
  installCRDs: true
ingress-nginx:
  enabled: true
  controller:
    config:
      brotli-level: "6"
      brotli-types: text/xml image/svg+xml application/x-font-ttf image/vnd.microsoft.icon
        application/x-font-opentype application/json font/eot application/vnd.ms-fontobject
        application/javascript font/otf application/xml application/xhtml+xml text/javascript
        application/x-javascript text/plain application/x-font-truetype application/xml+rss
        image/x-icon font/opentype text/css image/x-win-bitmap
      enable-brotli: "true"
    ingressClass: for-test-nginx
    ingressClassResource:
      name: for-test-nginx
kubernetes-dashboard:
  enabled: true
  ingress:
    enabled: true
    className: "for-test-nginx"
    annotations:
      kubernetes.io/tls-acme: 'true'
      cert-manager.io/issuer: for-test-issuer
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - kubernetes-dashboard.fortest.sorbapp.com
    tls:
      - secretName: kubernetes-dashboard-tls
        hosts:
          - kubernetes-dashboard.fortest.sorbapp.com
  metricsScraper:
    enabled: true
  metrics-server:
    enabled: false
is-pattern-1:
  enabled: false
am-pattern-1:
  enabled: false
grafana:
  enabled: false
  ingress:
    enabled: true
    hostname: grafana.fortest.sorbapp.com
    annotations:
      cert-manager.io/issuer: for-test-issuer
    tls: true  
    ingressClassName: "for-test-nginx"
mysql:
  enabled: false
#  auth:
#    rootPassword: "sbrQp10"
#    password: "sbrQp10"
  primary:
    configuration: |-
      [mysqld]
      default_authentication_plugin=mysql_native_password
      skip-log-bin
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mysql
      plugin_dir=/opt/bitnami/mysql/lib/plugin
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      datadir=/bitnami/mysql/data
      tmpdir=/opt/bitnami/mysql/tmp
      max_allowed_packet=16M
      bind-address=*
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      log-error=/opt/bitnami/mysql/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      slow_query_log=0
      slow_query_log_file=/opt/bitnami/mysql/logs/mysqld.log
      long_query_time=10.0
      [client]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mysql/lib/plugin
      [manager]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
phpmyadmin:
  enabled: false
  ingress:
    enabled: true
    hostname: phpmyadmin.fortest.sorbapp.com
    tls: true
    ingressClassName: "for-test-nginx"
    annotations:
      cert-manager.io/issuer: for-test-issuer
redis:
  enabled: false
  architecture: standalone
influxdb:
  enabled: false
  setDefaultUser:
    enabled: true
    user:
      username: admin

#### Solo es para el archivo NOTES.txt
ingress:
  enabled: false
