
apiVersion: v1
kind: Secret
metadata:
  name: rtdb-sync-sub-secret
type: Opaque
data:
  MQTT_HOST: |-
    {{ .Values.MQTT_HOST | b64enc }}
  MQTT_TOPIC: |-
    {{ .Values.MQTT_TOPIC | b64enc }}
  REDIS_HOST: |-
    {{ .Values.REDIS_HOST | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: rtdb-sync-pub-secret
type: Opaque
data:
  MQTT_HOST: |-
    {{ .Values.MQTT_HOST | b64enc }}
  MQTT_TOPIC: |-
    {{ .Values.MQTT_TOPIC | b64enc }}
  REDIS_HOST: |-
    {{ .Values.REDIS_HOST | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: hdfs-api-secret
type: Opaque
data:
  hdfs: |-
    {{ .Values.hdfs | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ml-trainer-api-secret
type: Opaque
data:
  livy: |-
    {{ .Values.livy | b64enc }}
  webhdfs: |-
    {{ .Values.webhdfs | b64enc }}
  HOSTALIASES_SANDBOX_IP: |-
    {{ .Values.HOSTALIASES_SANDBOX_IP | b64enc }}    

---
apiVersion: v1
kind: Secret
metadata:
  name: ml-trainer-ui-secret
type: Opaque
data:
  OPENID_CONNECT: |-
    {{ .Values.OPENID_CONNECT | b64enc }}
  proxies: |-
    {{ .Values.proxies | b64enc }}
  SESSION_SETTINGS: |-
    {{ .Values.SESSION_SETTINGS | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: preferences-api-secret
type: Opaque
data:
  sequelize: |-
    {{ .Values.sequelizep | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ng-api-gateway-secret
type: Opaque
data:
  proxy: |-
    {{ .Values.proxy | b64enc }}
  sequelize: |-
    {{ .Values.sequelizen | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: platform-ui-secret
type: Opaque
data:
  OPENID_CONNECT: |-
    {{ .Values.OPENID_CONNECTp | b64enc }}
  proxies: |-
    {{ .Values.proxiesp | b64enc }}
  SESSION_SETTINGS: |-
    {{ .Values.SESSION_SETTINGSp | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-to-influxdb-2y-secret
type: Opaque
data:
  influx: |-
    {{ .Values.influxm | b64enc }}
  mqtt: |-
    {{ .Values.mqttm | b64enc }}
  mqttTopic: |-
    {{ .Values.mqttTopicm | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-vernemq-local-tls
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.cacrt  }}
  tls.crt: {{ .Values.tlscrt  }}
  tls.key: {{ .Values.tlskey  }}


