apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: srv-cloud
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteMany
#  volumeMode: Filesystem
  storageClassName: azurefile
