ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: demo-com-nginx
  hosts:
    - host: code-server.demo-com.sorba.ai
      paths:
        - /
  tls:
    - secretName: code-server-tls
      hosts:
        - code-server.demo-com.sorba.ai
#  ingressClassName: "demo-com-nginx"
