USER-SUPPLIED VALUES:
admin:
  password: admin
  user: admin
ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: demo-com-nginx
  enabled: true
  hostname: dashboard.demo-com.sorba.ai
  tls: true
