application:
  DEPLOY_TYPE: "CLOUD"
  tenant: "demo.com"
  DATABASE_URL: '{ "database": "ml_trainer", "username": "root", "password": "sbrQp10", "host": "bit-mysql", "dialect": "mysql", "logging": false }'
  fsEntryPoint: "/srv/sorba/ml-trainer"
  REDIS: '{"port": 6379, "host": "bit-redis-master","db":0,"reconnectTime": 5000}'
  STORAGE: '{"useDefaults": false, "url": "http://influxdb-1-8:8086", "db": "sorba_ml", "batch_size": 1000, "user": "", "password": "", "version": "1.x", "bucket": "", "token": "", "org": ""}'
  DATASOURCE: '{"useDefaults": false, "url": "http://influxdb-1-8:8086", "db": "sorba_ml", "batch_size": 1000, "user": "", "password": "", "version": "1.x", "bucket": "", "token": "", "org": ""}'
  TREE: '{"useDefaults": false, "url":"http://sorbapp-tree-api-auto-deploy-app-gitlab.demo-com:5000"}'
  DASHBOARD: '{"useDefaults":false,"URL":"https://dashboard.demo-com.sorba.ai/api","host":"","port":3000,"user":"admin","password":"admin","org":"main"}'
  RAY: '{"cluster_mode":true,"master_address":"ray://ray.desa.sorbapp.com/","cluster_http":"https://ray.desa.sorbapp.com/","masters":[],"workers":[],"useDefaults":false}'
  MLAPI: "http://ml-trainer-api-ml-trainer-api.demo-com:5000"
image:
  pullPolicy: Always
  repository: registry.desa.sorbapp.com/sorbotics/ml-trainer/ml-trainer-api/development
  secrets:
  - name: gitlab-registry
  tag: latest
resources:
  requests: {}
ingress:
  enabled: false