application:
  database_url: mysql://root:4mz5IrvhZb@bitnami-mysql.for-test/tree
  redis: '{"port": 6379, "host": "bitnami-redis-master.for-test","db": 0,"reconnectTime":
    5000}'
image:
  pullPolicy: IfNotPresent
  repository: registry.desa.sorbapp.com/sorbotics/platform/ng-api-gateway/new-generation
  secrets:
  - name: gitlab-registry
  tag: latest
resources:
  requests: {}
ingress:
  enabled: true
  className: "nuevo1-nginx"
service:
  url: ng-api-gateway.nuevo1.sorbapp.com
  annotations:
    cert-manager.io/issuer: nuevo1-issuer  
#    kubernetes.io/ingress.class: nginx
#    kubernetes.io/tls-acme: 'true'
#    meta.helm.sh/release-name: ng-api-gateway
#    meta.helm.sh/release-namespace: nuevo1