wso2:
  deployment:
    wso2is:
      dockerRegistry: sorbaregistry.azurecr.io
      imageName: sorbotics/devops/wso2-alpine-is/master
      imageTag: latest
      imagePullSecrets: azure-registry
      replicas: 1
      resources:
        requests:
          memory: "2Gi"
          cpu: "100m"
        limits:
          memory: "4Gi"
          cpu: "200m"
      ingress:
        identity:
          hostname: "sorbais.jkl-com.sorbapp.com"
          annotations:
            cert-manager.io/issuer: jkl-com-issuer
            kubernetes.io/ingress.class: "jkl-com-nginx"
            kubernetes.io/tls-acme: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
  #subscription:
  #  password: password
  #  username: user
  #  email: admin@example.com