vernemq:
  enabled: false
cert-manager:
  enabled: false
  installCRDs: true
ingress-nginx:
  enabled: false
  controller:
    ingressClass: nuevo1-nginx
    ingressClassResource:
      name: nuevo1-nginx
kubernetes-dashboard:
  enabled: false
  ingress:
    enabled: true
    className: "nuevo1-nginx"
    annotations:
      kubernetes.io/tls-acme: 'true'
      cert-manager.io/issuer: nuevo1-issuer
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - kubernetes-dashboard.espn1-com.sorbapp.com
    tls:
      - secretName: kubernetes-dashboard-nuevo1-tls
        hosts:
          - kubernetes-dashboard.espn1-com.sorbapp.com
is-pattern-1:
  enabled: true
am-pattern-1:
  enabled: false
grafana:
  enabled: false
mysql:
  enabled: false
#  auth:
#    rootPassword: "sbrQp10"
#    password: "sbrQp10"
phpmyadmin:
  enabled: false
  ingress:
    enabled: true
    hostname: phpmyadmin.espn1-com.sorbapp.com
    ingressClassName: "nuevo1-nginx"
    annotations:
      cert-manager.io/issuer: nuevo1-issuer
redis:
  enabled: false
influxdb:
  enabled: false

tree-api:
  enabled: true
  application:
    database_url: mysql://root:4mz5IrvhZb@bitnami-mysql.for-test/tree
    redis: '{"port": 6379, "host": "bitnami-redis-master.for-test","db": 0,"reconnectTime": 5000}'
    CLOUD_GRAFANA_API: '{"URL":"http://bitnami-grafana:3000/api","USER":"admin","PASS":"sbrQp10"}'
    HDFS_URL: http://192.168.1.94:3003
    LICENSE_DECODER: '{"port": 8074,"host": "sorbapp-license-decoder-auto-deploy-app-gitlab","endpoint": "/api/decode"}'
    SORBA_INTEGRATION_AUTHORIZATION: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlNvcmJhIEludGVncmF0aW9uIiwiaWF0IjozNzM5NTcyMDAwMDB9.4A1X7l84wCJq7asgkGKaoYizlNBHnwGBm9Ex-YZRRzg'
    SORBA_INTEGRATION_URL: http://sorbapp-sorba-dashboard-comm-auto-deploy-app-gitlab:5000
  image:
    repository: sorbaregistry.azurecr.io/sorbotics/platform/tree-api/new-generation
    tag: latest
    pullPolicy: IfNotPresent
    secrets:
      - name: azure-registry 
  resources:
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
    requests: {}
  #    cpu: 100m
  #    memory: 128Mi
uuid-gen-api:
  enabled: true
#  image:
#    repository: sorbaregistry.azurecr.io/sorbotics/uuid-gen-api
#    tag: latest
#    pullPolicy: IfNotPresent
#    secrets:
#      - name: azure-registry 
events-middleware:
  enabled: false
identity-api:
  enabled: false
identity-ui:
  enabled: false
messages-mediator:
  enabled: false
ml-trainer-api:
  enabled: false
ml-ui:
  enabled: false
oee-engine:
  enabled: false
oee-ui:
  enabled: false
rtdb-sync-pub:
  enabled: false
rtdb-sync-sub:
  enabled: false
sde-socket:
  enabled: false
task-flows-backend:
  enabled: false
task-flows-frontend:
  enabled: false

