application:
  database_url: mysql://root:4mz5IrvhZb@bitnami-mysql.for-test/tree
  redis: '{"port": 6379, "host": "bitnami-redis-master.for-test","db": 0,"reconnectTime":
    5000}'
image:
  pullPolicy: IfNotPresent
  repository: registry.desa.sorbapp.com/sorbotics/mqtt-to-influxdb/8-comment-loging-output
  secrets:
  - name: gitlab-registry
  tag: f47567cb2147e84fb979c7491145e68ce1db828c
resources:
  requests: {}
ingress:
  enabled: false